<?php
get_header(); ?>

<?php
while ( have_posts() ) : the_post();
    // Get first category
    $categories = get_the_category();
    $cat_name = !empty($categories) ? esc_html($categories[0]->name) : 'Academic Guide';
?>

<div class="single-post-wrapper">
    <!-- Hero Section -->
    <div class="single-post-hero">
        <div class="container hero-container">
            <span class="single-post-category"><?php echo $cat_name; ?></span>
            <h1 class="single-post-title"><?php the_title(); ?></h1>
        </div>
    </div>

    <!-- Featured Image -->
    <?php if ( has_post_thumbnail() ) : ?>
    <div class="container">
        <div class="single-post-featured-img">
            <?php the_post_thumbnail('full', ['alt' => get_the_title()]); ?>
        </div>
    </div>
    <?php else: ?>
    <div class="single-post-no-img-spacer"></div>
    <?php endif; ?>

    <!-- Main Content & Sidebar -->
    <div class="container single-post-layout">
        
        <article class="single-post-main">
            <div class="entry-content" id="entry-content">
                
                <!-- Table of Contents Auto-Generated by JS -->
                <div class="toc-container" id="toc-container" style="display:none;">
                    <div class="toc-header">Table of Contents</div>
                    <ul class="toc-list" id="toc-list"></ul>
                </div>

                <?php the_content(); ?>

                <!-- Bottom CTA -->
                <div class="post-bottom-cta">
                    <h3>Ready to Elevate Your Grades?</h3>
                    <p>Our Native UK Experts are standing by to help you with 100% original, high-quality work tailored to your exact requirements.</p>
                    <div class="cta-buttons">
                        <a href="<?php echo home_url('/order'); ?>" class="btn btn-primary">Order Now - 50% Off</a>
                        <a href="<?php echo home_url('/#contact'); ?>" class="btn btn-outline">Submit Details</a>
                    </div>
                </div>
            </div> <!-- /.entry-content -->
        </article>

        <!-- Sidebar -->
        <aside class="single-post-sidebar">
            <div class="sidebar-sticky">
                
                <!-- Rapid Help Widget -->
                <div class="widget widget-help">
                    <div class="widget-help-icon">
                        <svg width="28" height="28" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z"></path></svg>
                    </div>
                    <h4>Need Urgent Help?</h4>
                    <p>Get a response within minutes from our academic experts.</p>
                    <a href="https://wa.me/447782200976" class="btn btn-whatsapp" target="_blank">Chat on WhatsApp</a>
                </div>

                <!-- Categories -->
                <div class="widget widget-categories">
                    <h4 class="widget-title">Categories</h4>
                    <ul>
                        <?php 
                        $cats = get_categories(array('orderby' => 'name', 'order' => 'ASC', 'hide_empty' => false));
                        foreach($cats as $cat) {
                            if($cat->name == 'Uncategorized') continue;
                            echo '<li><a href="'.get_category_link($cat->term_id).'">'.$cat->name.'</a></li>';
                        }
                        ?>
                    </ul>
                </div>

                <!-- Recent Posts -->
                <div class="widget widget-recent">
                    <h4 class="widget-title">Recent Articles</h4>
                    <ul class="recent-posts-list">
                        <?php 
                        $recent_args = array('posts_per_page' => 4, 'post__not_in' => array(get_the_ID()));
                        $recent_posts = new WP_Query($recent_args);
                        if($recent_posts->have_posts()) :
                            while($recent_posts->have_posts()): $recent_posts->the_post();
                            ?>
                            <li>
                                <a href="<?php the_permalink(); ?>">
                                    <?php if(has_post_thumbnail()): ?>
                                        <?php the_post_thumbnail('thumbnail', ['class' => 'recent-img']); ?>
                                    <?php else: ?>
                                        <div class="recent-img-placeholder"></div>
                                    <?php endif; ?>
                                    <span class="recent-title"><?php echo wp_trim_words(get_the_title(), 7, '...'); ?></span>
                                </a>
                            </li>
                            <?php
                            endwhile;
                            wp_reset_postdata();
                        endif;
                        ?>
                    </ul>
                </div>
                
                <!-- Sidebar Service CTA -->
                <div class="widget widget-service-cta">
                    <div class="service-cta-inner">
                        <h4>Premium Service</h4>
                        <p>Ensuring your dissertation is flawless before submission.</p>
                        <a href="<?php echo home_url('/dissertation-writing'); ?>">Explore Services &rarr;</a>
                    </div>
                </div>

            </div>
        </aside>
    </div> <!-- /.single-post-layout -->

    <!-- Related Posts -->
    <?php
    if ( !empty($categories) ) {
        $category_ids = array();
        foreach($categories as $individual_category) {
            $category_ids[] = $individual_category->term_id;
        }

        $args = array(
            'category__in'   => $category_ids,
            'post__not_in'   => array($post->ID),
            'posts_per_page' => 3,
            'ignore_sticky_posts' => 1,
            'orderby'        => 'rand'
        );
        $my_query = new WP_Query( $args );

        if( $my_query->have_posts() ) {
            ?>
            <section class="related-posts-section">
                <div class="container">
                    <div class="related-header">
                        <h2>Keep Reading</h2>
                        <p>More from the <strong><?php echo $cat_name; ?></strong> category</p>
                    </div>
                    <div class="blog-grid">
                        <?php
                        while( $my_query->have_posts() ) {
                            $my_query->the_post();
                            ?>
                            <div class="blog-card">
                                <a href="<?php the_permalink(); ?>">
                                    <?php if ( has_post_thumbnail() ) : ?>
                                        <?php the_post_thumbnail('medium_large', ['class' => 'blog-card-img']); ?>
                                    <?php else: ?>
                                        <div class="blog-card-img" style="background:#f8fafc; display:flex; align-items:center; justify-content:center; color:#94a3b8;">
                                            <span>No Image</span>
                                        </div>
                                    <?php endif; ?>
                                </a>
                                <div class="blog-card-content">
                                    <h3 class="blog-card-title"><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h3>
                                    <div class="blog-card-footer" style="border-top: none; padding-top:0;">
                                        <a href="<?php the_permalink(); ?>" class="read-more-btn">Read More &rarr;</a>
                                    </div>
                                </div>
                            </div>
                            <?php
                        }
                        wp_reset_postdata();
                        ?>
                    </div>
                </div>
            </section>
            <?php
        }
    }
    ?>

</div> <!-- /.single-post-wrapper -->

<!-- Dynamic JS for TOC -->
<script>
document.addEventListener('DOMContentLoaded', function() {
    const entryContent = document.getElementById('entry-content');
    const tocContainer = document.getElementById('toc-container');
    const tocList = document.getElementById('toc-list');
    
    if(entryContent && tocContainer && tocList) {
        const headings = entryContent.querySelectorAll('h2, h3');
        if(headings.length > 2) { 
            tocContainer.style.display = 'block';
            
            let currentH2Item = null;
            let currentH2Sublist = null;

            headings.forEach(function(heading, index) {
                if(!heading.id) {
                    heading.id = 'content-heading-' + index;
                }
                const li = document.createElement('li');
                li.className = 'toc-item toc-' + heading.tagName.toLowerCase();
                const a = document.createElement('a');
                a.href = '#' + heading.id;
                a.textContent = heading.textContent;
               
                a.addEventListener('click', function(e) {
                    e.preventDefault();
                    const targetInfo = document.getElementById(heading.id);
                    const yOffset = -120; 
                    const y = targetInfo.getBoundingClientRect().top + window.pageYOffset + yOffset;
                    window.scrollTo({top: y, behavior: 'smooth'});
                });

                li.appendChild(a);

                if (heading.tagName.toLowerCase() === 'h2') {
                    tocList.appendChild(li);
                    currentH2Item = li;
                    currentH2Sublist = null; // Reset sublist for the new H2
                } else if (heading.tagName.toLowerCase() === 'h3') {
                    if (currentH2Item) {
                        // Create a nested ul if it doesn't exist
                        if (!currentH2Sublist) {
                            currentH2Sublist = document.createElement('ul');
                            currentH2Sublist.className = 'toc-sublist';
                            currentH2Item.appendChild(currentH2Sublist);
                        }
                        currentH2Sublist.appendChild(li);
                    } else {
                        // If there is an H3 before any H2, just append it normally
                        tocList.appendChild(li);
                    }
                }
            });
        }
    }
});
</script>

<?php endwhile; ?>

<?php get_footer(); ?>
